blank_issues_enabled: false
contact_links:
  - name: Breeze Discord
    url: https://discord.com/invite/r85tk92YXZ
    about: Have questions about Breeze? Try asking on our Discord - this issue tracker is for reporting bugs or feature requests only
