blank_issues_enabled: false
contact_links:
  - name: Mist Discord
    url: https://discord.com/invite/r85tk92YXZ
    about: Have questions about Mist? Try asking on our Discord - this issue tracker is for reporting bugs or feature requests only
