blank_issues_enabled: false
contact_links:
  - name: Mist Discord
    url: https://mistbrowser.com/discord
    about: Have questions about Mist? Try asking on our Discord â€“ this issue tracker is for reporting bugs or feature requests only
